- hosts: all
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  become: yes
  roles:
    - { role: kubespray-defaults}
#    - { role: kubernetes/preinstall, tags: preinstall }
#    - { role: "container-engine", tags: "container-engine", when: deploy_container_engine|default(true) }
#    - { role: download, tags: download, when: "not skip_downloads" }
    - { role: etcdadm, tags: etcdadm, etcdadm_phase: install }
    - { role: groups-setup, tags: groups-setup }
    - { role: etcdadm, tags: etcdadm, etcdadm_phase: deploy }
    - { role: kubespray-etcd-compat, tags: kubespray-etcd-compat }
  environment: "{{proxy_env}}"

- include: kubespray-without-etcd-before-calico.yml

- include: kubespray-without-etcd-calico-and-after.yml
