- hosts: k8s-cluster:calico-rr:etcd
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  become: yes
  roles:
    - { role: kubespray-defaults}
    - { role: etcdadm, tags: etcdadm }
    - { role: kubespray-etcd-compat, tags: kubespray-etcd-compat }

- include: kubespray-without-etcd.yml
