- name: Check if etcdadm exists
  stat:
    path: "{{ bin_dir }}/etcdadm"
  register: etcdadm_stat

- name: Install dependency
  package:
    name: golang
    state: present
  when: not etcdadm_stat.exists

- name: Install etcdadm
  command: go get -u github.com/platform9/etcdadm
  when: not etcdadm_stat.exists
